### ISSUE TITLE
[Request AMMR Access]

### ISSUE THREAD

**Issue by AustinBLawrence** [AnyBody/ammr-doc#2]
I am a PhD Candidate at the University of Missouri in the US doing my dissertation research on the effect of torsion in the pelvis and lower limb on locomotor biomechanics, and I am very interested in the work you are doing with AnyBody and the tools you are developing for working with femoral torsion. 

Thank you! 

Austin Lawrence

**Comment by melund** [comment]
@AustinBLawrence I have given you access to the repository here. You may have to accept an invite. Afterwards you can get access here:

https://github.com/AnyBody/ammr

Let me know if I should help you with anything.

**Comment by melund** [comment]
@AustinBLawrence If you need a trial license for AnyBody and short intro to the system just let me know.
