### ISSUE TITLE
[Request AMMR Access]

### ISSUE THREAD

**Issue by Kiaulehn** [AnyBody/ammr-doc#4]
Dear Morten,

I came across your post in the AnyScript forum where you mentioned the Beta AMMR repository. 
I am very interested in contributing to the models and including them in my research, so I would like to ask you for access. 

With kind regards,
Viktoria Kiaulehn 
_University Hospital Aachen_

**Comment by melund** [comment]
Sound great Viktoria. I have given you access, and you should have received an invite. Once accepted, you can find the repo here: https://github.com/anybody/ammr

**Comment by Kiaulehn** [comment]
Perfect, thank you so much!
